### ISSUE TITLE
license

### ISSUE THREAD

**Issue by heshpdx** [ra397/Text-Similarity#1]
Hi! Can you attach an open-source license to this repository? I recommend the BSD 2-clause license: https://opensource.org/licenses/BSD-2-Clause

Thanks!

**Comment by ra397** [comment]
Done! Sorry for the late response.

**Comment by heshpdx** [comment]
Thanks so much! I am using this to verify the output of an optical-character-recognition software. It is ok if some characters are off, so your program helps with generating a score. So for example we can ensure the output is within 2% of all words being recognized.

**Comment by ra397** [comment]
Sounds good. Let me know if there are any issues.
